# ============================
# G-SCHOOLS CONNECT - Render Config
# ============================

services:
  - type: web
    name: gschools-connect
    env: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
